/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dnd;

/**
 *
 * @author RodrigoBoehme
 */
public class CriadorDePersonagem extends javax.swing.JFrame {

    /**
     * Creates new form CriadorDePersonagem
     */
    public CriadorDePersonagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        NomeCampo = new javax.swing.JTextField();
        BtnOrc = new javax.swing.JRadioButton();
        BtnHalf = new javax.swing.JRadioButton();
        BtnAnao = new javax.swing.JRadioButton();
        BtnElfo = new javax.swing.JRadioButton();
        btnGerarFicha = new javax.swing.JButton();
        ClasseComboBox = new javax.swing.JComboBox<>();
        LabelNome = new javax.swing.JLabel();
        LabelIdade = new javax.swing.JLabel();
        BtnHumano = new javax.swing.JRadioButton();
        LabelRaca = new javax.swing.JLabel();
        IdadeCampo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(BtnOrc);
        BtnOrc.setText("Orc");
        BtnOrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOrcActionPerformed(evt);
            }
        });

        buttonGroup1.add(BtnHalf);
        BtnHalf.setText("Halfling");
        BtnHalf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHalfActionPerformed(evt);
            }
        });

        buttonGroup1.add(BtnAnao);
        BtnAnao.setText("Anão");
        BtnAnao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnaoActionPerformed(evt);
            }
        });

        buttonGroup1.add(BtnElfo);
        BtnElfo.setText("Elfo");
        BtnElfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnElfoActionPerformed(evt);
            }
        });

        btnGerarFicha.setText("Gerar Ficha");
        btnGerarFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarFichaActionPerformed(evt);
            }
        });

        ClasseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guerreiro", "Mago", "Ladino", "Clerigo", "Barbaro" }));

        LabelNome.setText("Nome:");

        LabelIdade.setText("Idade:");

        buttonGroup1.add(BtnHumano);
        BtnHumano.setText("Humano");
        BtnHumano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHumanoActionPerformed(evt);
            }
        });

        LabelRaca.setText("Raça:");

        jLabel1.setText("Classe:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGerarFicha)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelIdade, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NomeCampo)
                            .addComponent(IdadeCampo)
                            .addComponent(ClasseComboBox, 0, 144, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnElfo)
                    .addComponent(BtnAnao)
                    .addComponent(BtnOrc)
                    .addComponent(BtnHumano)
                    .addComponent(BtnHalf)
                    .addComponent(LabelRaca))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelNome))
                    .addComponent(LabelRaca, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnOrc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAnao))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelIdade)
                            .addComponent(IdadeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ClasseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnElfo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnHumano, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnHalf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGerarFicha)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAnaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAnaoActionPerformed

    private void BtnElfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnElfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnElfoActionPerformed

    private void BtnHalfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHalfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnHalfActionPerformed

    private void BtnHumanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHumanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnHumanoActionPerformed

    private void BtnOrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOrcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnOrcActionPerformed

    private void btnGerarFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarFichaActionPerformed
        // TODO add your handling code here:
        String nome=NomeCampo.getText();
        String idade=IdadeCampo.getText();
        String raca;
        if(BtnHalf.isSelected()){raca="Halfling";}
        if(BtnHumano.isSelected()){raca="Humano";}
        if(BtnElfo.isSelected()){raca="Elfo";}
    }//GEN-LAST:event_btnGerarFichaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriadorDePersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriadorDePersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriadorDePersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriadorDePersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriadorDePersonagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BtnAnao;
    private javax.swing.JRadioButton BtnElfo;
    private javax.swing.JRadioButton BtnHalf;
    private javax.swing.JRadioButton BtnHumano;
    private javax.swing.JRadioButton BtnOrc;
    private javax.swing.JComboBox<String> ClasseComboBox;
    private javax.swing.JTextField IdadeCampo;
    private javax.swing.JLabel LabelIdade;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelRaca;
    private javax.swing.JTextField NomeCampo;
    private javax.swing.JButton btnGerarFicha;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
