/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfacegrafica;

/**
 *
 * @author RodrigoBoehme
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CampoNumero1 = new javax.swing.JTextField();
        CampoNumero2 = new javax.swing.JTextField();
        btn_soma = new javax.swing.JButton();
        btn_mult = new javax.swing.JButton();
        btn_sub = new javax.swing.JButton();
        btn_div = new javax.swing.JButton();
        LabelResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CampoNumero1.setText("Insira o primeiro numero");
        CampoNumero1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampoNumero1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CampoNumero1FocusLost(evt);
            }
        });
        CampoNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNumero1ActionPerformed(evt);
            }
        });

        CampoNumero2.setText("Insira o segundo numero");
        CampoNumero2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CampoNumero2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CampoNumero2FocusLost(evt);
            }
        });
        CampoNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNumero2ActionPerformed(evt);
            }
        });

        btn_soma.setText("Soma");
        btn_soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_somaActionPerformed(evt);
            }
        });

        btn_mult.setText("Mukt");
        btn_mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multActionPerformed(evt);
            }
        });

        btn_sub.setText("Subração");
        btn_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subActionPerformed(evt);
            }
        });

        btn_div.setText("Divss");
        btn_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divActionPerformed(evt);
            }
        });

        LabelResult.setText("Resultado:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelResult)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CampoNumero1)
                        .addComponent(CampoNumero2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_mult, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_div, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_soma, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_sub))))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(CampoNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sub)
                    .addComponent(btn_soma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_mult)
                    .addComponent(btn_div))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(LabelResult)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNumero1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_CampoNumero1ActionPerformed

    private void CampoNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNumero2ActionPerformed

    private void btn_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divActionPerformed
        // TODO add your handling code here:
        Double num1 = Double.valueOf(CampoNumero1.getText());
        Double num2 = Double.valueOf(CampoNumero2.getText());
        LabelResult.setText("Resultado: " + (num1 / num2));
    }//GEN-LAST:event_btn_divActionPerformed

    private void btn_somaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_somaActionPerformed
        // TODO add your handling code here:
        Double num1 = Double.valueOf(CampoNumero1.getText());
        Double num2 = Double.valueOf(CampoNumero2.getText());
        LabelResult.setText("Resultado: " + (num1 + num2));

    }//GEN-LAST:event_btn_somaActionPerformed

    private void btn_multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multActionPerformed
        // TODO add your handling code here:
        Double num1 = Double.valueOf(CampoNumero1.getText());
        Double num2 = Double.valueOf(CampoNumero2.getText());
        LabelResult.setText("Resultado: " + (num1 * num2));
    }//GEN-LAST:event_btn_multActionPerformed

    private void btn_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subActionPerformed
        // TODO add your handling code here:
        Double num1 = Double.valueOf(CampoNumero1.getText());
        Double num2 = Double.valueOf(CampoNumero2.getText());
        LabelResult.setText("Resultado: " + (num1 - num2));
    }//GEN-LAST:event_btn_subActionPerformed

    private void CampoNumero1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoNumero1FocusGained
        // TODO add your handling code here:
        if(CampoNumero1.getText().equals("Insira o primeiro numero")){
        CampoNumero1.setText("");
        }
    }//GEN-LAST:event_CampoNumero1FocusGained

    private void CampoNumero1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoNumero1FocusLost
        // TODO add your handling code here:
                if(CampoNumero1.getText().equals("")){
        CampoNumero1.setText("Insira o primeiro numero");
        }
    }//GEN-LAST:event_CampoNumero1FocusLost

    private void CampoNumero2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoNumero2FocusGained
        // TODO add your handling code here:
                if(CampoNumero2.getText().equals("Insira o segundo numero")){
        CampoNumero2.setText("");
        }
    }//GEN-LAST:event_CampoNumero2FocusGained

    private void CampoNumero2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CampoNumero2FocusLost
        // TODO add your handling code here:
                if(CampoNumero2.getText().equals("")){
        CampoNumero2.setText("Insira o segundo numero");
        }
    }//GEN-LAST:event_CampoNumero2FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoNumero1;
    private javax.swing.JTextField CampoNumero2;
    private javax.swing.JLabel LabelResult;
    private javax.swing.JButton btn_div;
    private javax.swing.JButton btn_mult;
    private javax.swing.JButton btn_soma;
    private javax.swing.JButton btn_sub;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
